apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mssql
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: lab-mssql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-sa-password
                  key: mssql-sa-password
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/opt/mssql"
              name: volume
              readOnly: false
            - name: secrets-store
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: mssql-pvc
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "keyvault-secrets" # This should match the name of your SecretProviderClass
      restartPolicy: Always