apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mssql
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: lab-mssql
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: P@ssw0rd2023!
          image: mcr.microsoft.com/mssql/server:2022-latest
          ports:
            - containerPort: 1433
              protocol: TCP
          volumeMounts:
          - mountPath: "/var/opt/mssql"
            name: volume
            readOnly: false
      volumes:
      - name: volume
        persistentVolumeClaim:
          claimName: mssql-pvc
      restartPolicy: Always