apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console
  name: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
        - name: lab-console
          env:
            - name: RabbitMQ__Hostname
              valueFrom:
                configMapKeyRef:
                  key: rabbitmq-hostname
                  name: global-config
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-password
                  name: global-secrets
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-username
                  name: global-secrets
          image: matthieuf/pubsub-console:1.0
      restartPolicy: Always
