apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: keyvault-secrets # needs to be unique per namespace
spec:
  provider: azure
  parameters:
    userAssignedIdentityID: 476c9d3f-1395-444c-88c3-a15915306905 # Setting this to use workload identity ClientID
    keyvaultName: kv-4mi-mfo # Set to the name of your key vault
    tenantId: 1e2f522c-2662-4a18-938a-8b61a1ab92d1 # The tenant ID of the key vault
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    objects: |
      array:
        - |
          objectName: rabbitmq-username
          objectType: secret
        - |
          objectName: rabbitmq-password
          objectType: secret
        - |
          objectName: mssql-sa-password
          objectType: secret
  secretObjects:
    - secretName: mssql-sa-password  # name of the secret to create in the pod
      type: Opaque
      data:
        - objectName: mssql-sa-password # name of the mounted content to sync. this could be the object name or object alias
          key: mssql-sa-password
    - secretName: rabbitmq-password
      type: Opaque
      data:
        - objectName: rabbitmq-password # name of the mounted content to sync. this could be the object name or object alias
          key: rabbitmq-password
    - secretName: rabbitmq-username
      type: Opaque
      data:
        - objectName: rabbitmq-username # name of the mounted content to sync. this could be the object name or object alias
          key: rabbitmq-username