apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
type: Opaque
data:
  rabbitmq-username: YWRtaW4K # base64 encoded value of 'admin'
  rabbitmq-password: YWRtaW4K # base64 encoded value of 'admin'
