apiVersion: v1
kind: Secret
metadata:
  name: global-secrets
type: Opaque
data:
  rabbitmq-username: YWRtaW4K # base64 encoded value of 'admin'
  rabbitmq-password: YWRtaW4K # base64 encoded value of 'admin'
  mssql-sa-password: UEBzc3cwcmQyMDIzIQ== # base64 encoded value of 'P@ssw0rd2023!'